name: demo_app_2
description: "tp2"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.22.0" # optionnel mais recommandé

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2          # (optionnel) version + récente compatible Dart 3
  flutter_dotenv: ^5.1.0
  intl: any
  weather_icons: ^3.0.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
